# Generated by Django 3.1.4 on 2022-03-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=32, verbose_name='姓名')),
                ('tel', models.CharField(max_length=10, verbose_name='連絡電話')),
                ('role', models.CharField(max_length=20, verbose_name='職稱')),
            ],
        ),
    ]
