# Generated by Django 3.1.4 on 2022-03-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cardid',
            field=models.CharField(default='', max_length=30, verbose_name='卡號'),
            preserve_default=False,
        ),
    ]
