# Generated by Django 2.2.27 on 2022-03-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20220308_2055'),
        ('teacher', '0002_teacher_cardid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='test',
            field=models.ManyToManyField(to='classes.Classes'),
        ),
    ]
