# Generated by Django 2.2.27 on 2022-03-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0004_auto_20220314_1509'),
        ('teacher', '0003_teacher_tea_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.DateTimeField(null=True, verbose_name='登記時間')),
                ('end', models.DateTimeField(null=True, verbose_name='結束使用時間')),
                ('workstatus', models.IntegerField(choices=[(0, '即將使用'), (1, '使用中'), (2, '使用完畢')], default=0, verbose_name='資料狀態')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
    ]
