# Generated by Django 3.1.4 on 2022-03-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0002_auto_20220301_1622'),
        ('teacher', '0002_teacher_cardid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.DateTimeField(auto_now_add=True, verbose_name='登記時間')),
                ('end', models.DateTimeField(null=True, verbose_name='結束使用時間')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
