# Generated by Django 3.1.4 on 2022-03-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='classes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
            preserve_default=False,
        ),
    ]
