# Generated by Django 3.1.4 on 2022-03-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20220308_2055'),
        ('log', '0002_auto_20220316_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='classes',
            field=models.ForeignKey(default=305, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
            preserve_default=False,
        ),
    ]
