# Generated by Django 3.1.4 on 2022-03-26 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20220323_1625'),
        ('log', '0003_log_classes'),
    ]

    operations = [
    ]
