# Generated by Django 2.2.27 on 2022-03-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0061_auto_20220315_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='reserve',
            field=models.DateTimeField(null=True, verbose_name='登記時間'),
        ),
        migrations.AlterField(
            model_name='log',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
        migrations.AlterField(
            model_name='log',
            name='workstatus',
            field=models.IntegerField(choices=[(0, '即將使用'), (1, '使用中'), (2, '使用完畢')], default=0, verbose_name='資料狀態'),
        ),
    ]
