# Generated by Django 3.1.4 on 2022-03-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='model',
            new_name='name',
        ),
    ]
