# Generated by Django 3.1.4 on 2022-03-05 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20220301_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='preface',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='教室圖片'),
            preserve_default=False,
        ),
    ]
