# Generated by Django 2.2.27 on 2022-03-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_auto_20220308_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=32, verbose_name='姓名')),
                ('cardid', models.CharField(max_length=30, verbose_name='卡號')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='stu_classes',
            field=models.ManyToManyField(through='student.Student_Classes', to='classes.Classes'),
        ),
    ]
