# Generated by Django 2.2.27 on 2022-03-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20220308_2055'),
        ('student', '0002_auto_20220312_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Classes')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(through='student.Student_Classes', to='classes.Classes'),
        ),
        migrations.AddField(
            model_name='student_classes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
