# Generated by Django 2.2.27 on 2022-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20220308_2055'),
        ('student', '0003_auto_20220312_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.AddField(
            model_name='student',
            name='stu_classes',
            field=models.ManyToManyField(through='student.Student_Classes', to='classes.Classes'),
        ),
    ]
